const fs = require('fs');
const path = require('path');

// Path to the sidebars.ts file
const sidebarsPath = path.resolve(__dirname, '../../docusaurus-site/sidebars.ts');

// Read the sidebars.ts file
let sidebarsContent = fs.readFileSync(sidebarsPath, 'utf-8');

// Function to add the OpenAPI link for the specific project
function addOpenApiLink(projectName) {
  console.log('projectName', projectName);
  
  const openApiLink = `
        {
          type: 'link',
          label: 'API Documentation',
          href: '/${projectName}-api/',
        },
  `;

  // Check if the category already exists
  const categoryExists = sidebarsContent.includes(`label: '${projectName}'`);

  if (categoryExists) {
    console.log(`Category ${projectName} already exists.`);
    // Ensure the OpenAPI link is not already present
    if (!sidebarsContent.includes(openApiLink.trim())) {
      sidebarsContent = sidebarsContent.replace(
        new RegExp(`(label: '${projectName}',\\s*items: \\[)([^]*?)(\\])`, 'g'),
        `$1$2${openApiLink}$3`
      );
    }
  } else {
    console.log(`Category ${projectName} does not exist, creating it.`);
    // If the category doesn't exist, create it
    const newCategory = `
    {
      type: 'category',
      label: '${projectName}',
      items: [
        {
          type: 'autogenerated',
          dirName: '${projectName}',
        },
        ${openApiLink}
      ],
    },`;

    // Add the new category to the sidebar
    sidebarsContent = sidebarsContent.replace(
      /(documentationSidebar: \[)([^]*?)(\],)/,
      `$1$2${newCategory}$3`
    );
  }

  console.log(`Updated content:\n${sidebarsContent}`);

  // Write the updated content back to sidebars.ts
  fs.writeFileSync(sidebarsPath, sidebarsContent);
}

// Example usage: Add a link for the triggered project
const triggeredProjectName = process.argv[2]; // Pass project name as argument
addOpenApiLink(triggeredProjectName);
