import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Auto-generate a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Auto-generate from the root docs folder
    },
    {
      type: 'category',
      label: 'G Taxonomy Products Categorizer',
      items: [
        {
          type: 'autogenerated',
          dirName: 'g-taxonomy-products-categorizer', // Auto-generate for this specific directory
        },
        {
          type: 'link',
          label: 'API Documentation',
          href: '/g-taxonomy-products-categorizer-api/', // Link to the OpenAPI documentation
        },
      ],
    },
  ],

  // You can also define other sidebars manually if needed
  /*
  anotherSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Another Category',
      items: ['another-doc'],
    },
  ],
   */
};

export default sidebars;
