import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  documentationSidebar: [
    {
      type: 'category',
      label: 'g-taxonomy-products-categorizer',
      items: [
        {
          type: 'autogenerated',
          dirName: 'g-taxonomy-products-categorizer',
        },
        
        {
          type: 'link',
          label: 'API Documentation',
          href: '/g-taxonomy-products-categorizer-api/',
        },
  
      ],
    },],
};

export default sidebars;
