openapi: 3.0.1
info:
  title: Example API
  description: This is an example API documentation.
  version: 1.0.3
servers:
  - url: https://test.execute-api.us-east-1.amazonaws.com/dev
    variables:
      your-api-id:
        default: api-id-placeholder
      your-region:
        default: region-placeholder
      stage:
        default: dev
paths:
  /:
    get:
      summary: Root path
      responses:
        '200':
          description: A simple static website - test
  /date:
    get:
      summary: Get the current date - test
      responses:
        '200':
          description: Returns the current date
